name: leetcode
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          mkdir -p build
          cd build
          conan install .. --build outdated
      - name: configure
        run: |
          cd build
          cmake -D ENABLE_CLANG_TIDY:BOOL=OFF -D ENABLE_CLANG_FORMAT:BOOL=OFF ..
      - name: build
        run: |
          cd build
          cmake --build .
      - name: test
        run: |
          cd build
          cmake --build . --target test
